### PR TITLE
Functional Full-Text Shell (ftsh) Implementation

### PR DESCRIPTION
**Pull request by mbronckers**
Tasks completed:
- [x] Added a basic functional shell
- [x] Implemented error handling (can be changed depending on style choice)
- [x] Implemented full-text functions
- [x] Created appropriate directories
- [x] Added initial test files
- [x] Added and configured Makefile for ftsh
- [x] Added .gitignore file

Bugs fixed:
- [x] Fixed `-lreadline` compile error
- [x] Fixed `Ctrl-D` command to exit shell

### CODE REVIEW

**Comment by MoldyAppleJuice** [comment]
Readline isn't included in directory, causing error with make.

**Comment by mbronckers** [comment]
@mpcsh said to remove the #include <readline/readline.h> line, so I commented that out. Let me know if that resolves it.

**Comment by mbronckers** [comment]
I deleted `.dSYM` file removal and put `-lreadline` in a `LDLIBS` variable after creating the binary files, which should fix the compile error on Linux machines.

**Comment by mbronckers** [comment]
Upon review, I implemented a few things:
- I adjusted my Makefile to be linux specific (remove the .dSYM file removal).
- Fixed the handling of `Ctrl-D` to exit the ftsh shell
- Added a .gitignore file to ignore executables and .o files

**Pull request closed without merging**
