### PR TITLE
Ruolin/mock trie

### PR DESCRIPTION
**Pull request by RuolinZheng08**
I finished implementing mock-trie operations and corresponding Unit tests.
The current-in-use return_matches_m is a mock one that returns a string; in future steps it would 
return a dbll.
There seems to be some merge conflict we need to manually solve. Plz let me know what you guys think!

### CODE REVIEW

**Comment by mpcsh** [comment]
After @cdignan and @MoldyAppleJuice review this, someone (not me) should do the merge into dev to get experience with resolving merge conflicts. To whoever ends up doing this: don't use the "Resolve conflicts" button in GitHub - instead use the command line. There are instructions if you click the link for "command line" in the "Use the web editor or the command line to resolve conflicts" thing next to the "Resolve conflicts" button. Inspect the output of those commands carefully, and use `man git-fetch`, `man git-checkout`, `man git-merge`, etc to understand exactly what each command does.

**Comment by cdignan** [comment]
When I compiled and ran it, it seg faulted. Did you have this problem? That would be the first thing to fix, let me know if you can't fix it, in which case I can try. Once that problem is fixed then I think I'll be able to give better feedback.

**Comment by RuolinZheng08** [comment]
@cdignan I guess you ran the libmtrie.so? It is a library and not a binary. The tests/test-mtrie works just fine for me.
Please follow the steps in README and let me know if it works.
File Usage
run 'make' in fulltext/
run 'make' in fulltext/tests
run './test-mtrie' in fulltext/tests

**Comment by cdignan** [comment]
Ah ok, sorry for the delay here, everything looks good as far as I can tell!

**Comment by mpcsh** [comment]
@RuolinZheng08 while there's no mechanism to block merging until this happens, you should wait for approving reviews from all requested reviewers before merging. It looks like you requested reviews from Cameron and Christina, but didn't wait for Christina's review. You should either have waited for her review or only requested Cameron's review.

**Pull request merged**
