### PR TITLE
Ruolin/single word read until match

### PR DESCRIPTION
**Pull request by RuolinZheng08**
I experimented with various I/O functions and wonder if read_until_next_match can be implemented with getline() and strtok() like this.

Usage:
run make filetest in fulltext/
./filetest
type 'next' to display the next word, other commands will be ignored

Please let me know what you think!

### CODE REVIEW

**Comment by mpcsh** [comment]
@mbronckers so is this an approving review or are you requesting changes? I don't really like that GitHub gives the "general review" option.

**Comment by mbronckers** [comment]
Requesting changes. There are still some bugs / incompatibilities that make it unable to merge into dev.

**Comment by mpcsh** [comment]
Cool, can you go ahead and change your review status to "changes requested"? It helps me see which PRs are ready for my review.

**Comment by mpcsh** [comment]
Oh wait, this is a PR into dev - I'm going to remove myself from the requested reviewers. @RuolinZheng08 unless there's a pre-discussed reason, please only tag me on PRs into master.

**Comment by mbronckers** [comment]
Can't compile. `make filetest` is broken.

**Pull request closed without merging**
